# Generated by Django 6.0.1 on 2026-01-31 10:47

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='الاسم')),
                ('name_en', models.CharField(max_length=100, verbose_name='الاسم بالإنجليزية')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='الرابط')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
            ],
            options={
                'verbose_name': 'فئة المدونة',
                'verbose_name_plural': 'فئات المدونة',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='العنوان')),
                ('title_en', models.CharField(max_length=200, verbose_name='العنوان بالإنجليزية')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='الرابط')),
                ('excerpt', models.TextField(max_length=300, verbose_name='ملخص')),
                ('excerpt_en', models.TextField(max_length=300, verbose_name='ملخص بالإنجليزية')),
                ('content', tinymce.models.HTMLField(verbose_name='المحتوى')),
                ('content_en', tinymce.models.HTMLField(verbose_name='المحتوى بالإنجليزية')),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='blog/images/', verbose_name='الصورة المميزة')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('published', 'منشور')], default='draft', max_length=20, verbose_name='الحالة')),
                ('is_featured', models.BooleanField(default=False, verbose_name='مميز')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='عدد المشاهدات')),
                ('meta_description', models.CharField(blank=True, max_length=160, verbose_name='وصف ميتا')),
                ('meta_keywords', models.CharField(blank=True, max_length=255, verbose_name='كلمات مفتاحية')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ النشر')),
            ],
            options={
                'verbose_name': 'مقالة',
                'verbose_name_plural': 'المقالات',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PostComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='المحتوى')),
                ('is_approved', models.BooleanField(default=True, verbose_name='موافق عليه')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'تعليق',
                'verbose_name_plural': 'التعليقات',
                'ordering': ['created_at'],
            },
        ),
    ]
