# Generated by Django 6.0.1 on 2026-02-02 10:17

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcategory',
            name='description_ar',
            field=models.TextField(blank=True, null=True, verbose_name='الوصف'),
        ),
        migrations.AddField(
            model_name='blogcategory',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='الوصف'),
        ),
        migrations.AddField(
            model_name='blogcategory',
            name='name_ar',
            field=models.CharField(max_length=100, null=True, verbose_name='الاسم'),
        ),
        migrations.AddField(
            model_name='post',
            name='content_ar',
            field=tinymce.models.HTMLField(null=True, verbose_name='المحتوى'),
        ),
        migrations.AddField(
            model_name='post',
            name='excerpt_ar',
            field=models.TextField(max_length=300, null=True, verbose_name='ملخص'),
        ),
        migrations.AddField(
            model_name='post',
            name='title_ar',
            field=models.CharField(max_length=200, null=True, verbose_name='العنوان'),
        ),
        migrations.AlterField(
            model_name='blogcategory',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='الاسم'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content_en',
            field=tinymce.models.HTMLField(null=True, verbose_name='المحتوى'),
        ),
        migrations.AlterField(
            model_name='post',
            name='excerpt_en',
            field=models.TextField(max_length=300, null=True, verbose_name='ملخص'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='العنوان'),
        ),
    ]
