# Generated by Django 6.0.1 on 2026-01-31 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='الاسم')),
                ('name_en', models.CharField(max_length=100, verbose_name='الاسم بالإنجليزية')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='الرابط')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'فئة',
                'verbose_name_plural': 'الفئات',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='العنوان')),
                ('title_en', models.CharField(max_length=200, verbose_name='العنوان بالإنجليزية')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='الرابط')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('description_en', models.TextField(verbose_name='الوصف بالإنجليزية')),
                ('thumbnail', models.ImageField(upload_to='courses/thumbnails/', verbose_name='صورة الدورة')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر')),
                ('difficulty', models.CharField(choices=[('beginner', 'مبتدئ'), ('intermediate', 'متوسط'), ('advanced', 'متقدم')], default='beginner', max_length=20, verbose_name='مستوى الصعوبة')),
                ('duration_hours', models.PositiveIntegerField(default=0, verbose_name='مدة الدورة (بالساعات)')),
                ('is_published', models.BooleanField(default=False, verbose_name='منشورة')),
                ('is_featured', models.BooleanField(default=False, verbose_name='مميزة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'دورة',
                'verbose_name_plural': 'الدورات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التسجيل')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('progress', models.PositiveIntegerField(default=0, verbose_name='نسبة الإنجاز')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإكمال')),
            ],
            options={
                'verbose_name': 'تسجيل',
                'verbose_name_plural': 'التسجيلات',
                'ordering': ['-enrolled_at'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='العنوان')),
                ('title_en', models.CharField(max_length=200, verbose_name='العنوان بالإنجليزية')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('video_url', models.URLField(blank=True, verbose_name='رابط الفيديو')),
                ('video_file', models.FileField(blank=True, null=True, upload_to='courses/videos/', verbose_name='ملف الفيديو')),
                ('duration_minutes', models.PositiveIntegerField(default=0, verbose_name='المدة (بالدقائق)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('is_preview', models.BooleanField(default=False, verbose_name='درس تجريبي')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'درس',
                'verbose_name_plural': 'الدروس',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='التقييم')),
                ('comment', models.TextField(blank=True, verbose_name='التعليق')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'تقييم',
                'verbose_name_plural': 'التقييمات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='المحتوى')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='courses.comment', verbose_name='رد على')),
            ],
            options={
                'verbose_name': 'تعليق',
                'verbose_name_plural': 'التعليقات',
                'ordering': ['created_at'],
            },
        ),
    ]
