# Generated by Django 6.0.1 on 2026-02-02 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description_ar',
            field=models.TextField(blank=True, null=True, verbose_name='الوصف'),
        ),
        migrations.AddField(
            model_name='category',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='الوصف'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ar',
            field=models.CharField(max_length=100, null=True, verbose_name='الاسم'),
        ),
        migrations.AddField(
            model_name='course',
            name='description_ar',
            field=models.TextField(null=True, verbose_name='الوصف'),
        ),
        migrations.AddField(
            model_name='course',
            name='title_ar',
            field=models.CharField(max_length=200, null=True, verbose_name='العنوان'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='description_ar',
            field=models.TextField(blank=True, null=True, verbose_name='الوصف'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='الوصف'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='title_ar',
            field=models.CharField(max_length=200, null=True, verbose_name='العنوان'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='الاسم'),
        ),
        migrations.AlterField(
            model_name='course',
            name='description_en',
            field=models.TextField(null=True, verbose_name='الوصف'),
        ),
        migrations.AlterField(
            model_name='course',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='العنوان'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='العنوان'),
        ),
    ]
